### ISSUE TITLE
Could not connect / Not found (self-hosted gitlab-ce)

### ISSUE THREAD

**Issue by hlidotbe** [Mikescops/gitlab-notify-extension#8]
Hi,

The extension is not working for me with a self-hosted gitlab-ce. When testing the connection in the preferences I get a "Could not connect" and the popup shows a "Not found" in red. Trying to debug I see a LOT of request on `.../approvals` which results in a 404 (expected as this is a paying feature). The MR endpoint is returning results correctly so I assume the error comes from the approvals.

Tested on Firefox and Chrome, same issue.

**Comment by Mikescops** [comment]
Hello,
Thanks for reporting this, I never tested with the Community version and didn't checked if it's a paid feature (my mistake).
I'll will test this asap and provide a workaround.

**Comment by apoiget** [comment]
It works for me with GitLab Community Edition 12.9.2 with token "api, read_user" and Gitlab host address in http ( http://myGitlabServer.local ). Maybe issue to manage certificates

**Comment by Mikescops** [comment]
GitLab API is throwing "Not Found" for any error, and for instance when the token doesn't have enough rights.
I will try to reproduce but @hlidotbe I'm interested in knowing your GitLab version and if you can share a screenshot of the "Network" tab it would help a lot.
Thanks guys.

**Comment by hlidotbe** [comment]
Sure things

Gitlab version:  12.10.3 (e01ceba1b49)

Network tab: 
![gitlab](https://user-images.githubusercontent.com/193949/81662860-7597fe80-943e-11ea-89ad-70b688f8c010.png)

As you can see it can call some endpoints without issue but makes a lot of /approvals calls 

I've checked twice and my token has api and read_user.

**Comment by sebclick** [comment]
Hello,

Same problem for me with Gitlab CE 11.6.10.
Like @hlidotbe, I have 404 errors on /approvals endpoint.

**Comment by apoiget** [comment]
I think the issue is due to approval it throw an error:
![image](https://user-images.githubusercontent.com/12910858/81664929-55693f00-9440-11ea-9d9d-6fe3a250af20.png)

https://github.com/Mikescops/gitlab-notify-extension/blob/master/src/background/index.ts#L85
https://github.com/Mikescops/gitlab-notify-extension/blob/master/src/background/index.ts#L192

**Comment by Mikescops** [comment]
Thanks everyone, my workaround will be to provide an option to specify when you are using the community edition (and then remove the related features).

**Comment by Mikescops** [comment]
Ok I could reproduce on my personal instance. 

Downside of the workaround is obviously you won't have the check marks when a PR is approved because it's a premium feature. Everything looks like to work well.

I will provide new builds asap. Expect Firefox version release soon and Chrome in a week or so due to review on their side.

**Comment by Mikescops** [comment]
FYI: https://github.com/Mikescops/gitlab-notify-extension/releases/tag/v1.3.0

**Comment by hlidotbe** [comment]
Excellent, will report as soon as it's available. Obviously premium features are not expected but quick access and notification are already great.

**Comment by Mikescops** [comment]
Update folks,
Release is already available on Firefox https://addons.mozilla.org/en-US/firefox/addon/gitlab-notify/
and under review for Chrome.

Enjoy :tada:

**Comment by hlidotbe** [comment]
And it works perfectly now! Thanks a lot!
